name: Kernel Releases

on:
  push:
    branches: [ jupyter ]
  pull_request:
    branches: [ jupyter ]

  workflow_dispatch:

jobs:
  kernelpublish:
    name: Publish kernel for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: Dodu
            asset_name: Dodu-jupyter-linux-amd64
          - os: windows-latest
            artifact_name: Dodu.exe
            asset_name: Dodu-jupyter-kernel-windows-amd64
          - os: macos-latest
            artifact_name: Dodu
            asset_name: Dodu-jupyter-macos-amd64

    steps:
    - uses: actions/checkout@v2
    
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.3'
        cabal-version: '3.2'
        
    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
          
    - name: Install dependencies
      run: |
        cabal update
        cabal install exe:Dodu --install-method=copy --overwrite-policy=always --installdir=dist
    - name: Build
      run: cabal build
    # - name: Run tests
    #  run: cabal test all
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./dist/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        tag: ${{ github.ref }}
        overwrite: true
